### PR TITLE
Adding support for Laravel 5.1

### PR DESCRIPTION
**Pull request by ryantology**

### CODE REVIEW

**Comment by ryantology** [comment]
@braseidon So, I normalized this a lot. It's not quite as readable with the use of the `->map()` methods but the output is one simple array of the merged inventory. I basically ported the code from `node-trade-offers` https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/index.js#L369 into this. 
Also handles empty / private inventory.

Feel free to reject the changes if you don't agree. Just made this PR for your review / comment.

Usage:

``` php
    $inventory->loadInventory($steamid, $appid, $context);
    if ($inventory->success == false) {
        if (isset($inventory->error)) {
            return $inventory->error;
        } else {
            return 'Inventory Empty';
        }
    }
    return view('inventory.index')->with('items', $inventory->inventory)
```

**Comment by unr** [comment]
:+1: @braseidon

**Comment by braseidon** [comment]
@ryantology I'm cool with the Laravel 5.1 updates, but I think the others should be a separate pull request. Sorry for not adding 5.1 support myself - it's been a while since I've worked on this.

Would you mind separating your updates and we can discuss your other changes in a new pull request?

**Comment by ryantology** [comment]
Ahh good point. Will separate them tonight.

**Pull request closed without merging**
